name: Build & deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      # - name: Deploy to GH Pages
      #   run: |
      #     git config --global user.email parthkumar@simformsolutions.com
      #     git config --global user.name parth-simform
      #     git remote set-url origin https://github.com/mobile-simformsolutions/JsonSchemaformExample.git
      #     npm run deploy
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
